### ISSUE TITLE
Solution for modules-marketplace

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/NEST-roadmap#51]
- determine the optimal way to store the information about modules available for teal app creator
- make a prototype of function to return markeplace modules.
- (recommendation) store the information in the package
- It could be a manual, automatic or semi-automatic
- Don't depend on a namespaces and names convention - should be bulletproof 

Suggestion:

`teal.modules.clinical::available_modules()` or something similar

**Comment by Polkas** [comment]
I do not agree with some assumptions where "Don't depend on a namespaces and names convention - should be bulletproof
" is most surprising for me.

so for example we using a naming convention in the pkgdown , so why not to use it for this purpose too.

```
  - title: General functionality modules
    contents:
      - matches('tm_[a-z][a-z]')
 
    - title: Modules for tables
    contents:
      - starts_with('tm_t_')

  - title: Modules for plots
    contents:
      - starts_with('tm_g_')
      - starts_with('tm_a_')
```

My idea is to use here the namespaces of each concern pacakge as I show before:

```
tmc_n <- asNamespace("teal.modules.clinical")

modules_names <- grep("tm_", ls(tmc_n), value = T)
tm_formals <- lapply(modules_names, function(x) formals(tmc_n[[x]]))
names(tm_formals) <- modules_names
tm_formals
```

**Comment by gogonzo** [comment]
@Polkas first step is less difficult to decide on searching namespace. As you noted above, we are pretty consistent with the naming but the problem will occur when we decide to distinguish end describe formals.
Imagine tm_g_xxx
```yaml
tm_g_xxx:
  params:
    a: data_extract_spec
    b: character
    c: logical
``` 
In the latter stages of the design we will have to deduct what to pass to the module arguments. Dependency on the namespace doesn't give us any guarantee that we (our algorithm) will correctly guess the type of the argument. This is why we need to be explicit. It should be either some file with content of a function returning needed settings.
